#spring:
#  datasource:
#    url: jdbc:h2:./db_dev;MODE=MySQL
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_dev
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver